Rails/config/routes.rb
Bca::Application.routes.draw do
  devise_for :cyclists

  resources :teams

  resources :business_sizes

  resources :competitions

end

Rails/app/models/business_size.rb
class BusinessSize < ActiveRecord::Base
  attr_accessible :name, :description
end

Rails/app/models/competition.rb
class Competition < ActiveRecord::Base
  attr_accessible :description, :enddate, :name, :startdate
end

Rails/app/models/cyclist.rb
class Cyclist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

Rails/app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :description, :name, :size
end

Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Rails/app/controllers/business_sizes_controller.rb
class BusinessSizesController < ApplicationController
  # GET /business_sizes
  # GET /business_sizes.json
  def index
    @business_sizes = BusinessSize.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @business_sizes }
    end
  end

  # GET /business_sizes/1
  # GET /business_sizes/1.json
  def show
    @business_size = BusinessSize.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business_size }
    end
  end

  # GET /business_sizes/new
  # GET /business_sizes/new.json
  def new
    @business_size = BusinessSize.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business_size }
    end
  end

  # GET /business_sizes/1/edit
  def edit
    @business_size = BusinessSize.find(params[:id])
  end

  # POST /business_sizes
  # POST /business_sizes.json
  def create
    @business_size = BusinessSize.new(params[:business_size])

    respond_to do |format|
      if @business_size.save
        format.html { redirect_to @business_size, notice: 'Business size was successfully created.' }
        format.json { render json: @business_size, status: :created, location: @business_size }
      else
        format.html { render action: "new" }
        format.json { render json: @business_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /business_sizes/1
  # PUT /business_sizes/1.json
  def update
    @business_size = BusinessSize.find(params[:id])

    respond_to do |format|
      if @business_size.update_attributes(params[:business_size])
        format.html { redirect_to @business_size, notice: 'Business size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business_size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_sizes/1
  # DELETE /business_sizes/1.json
  def destroy
    @business_size = BusinessSize.find(params[:id])
    @business_size.destroy

    respond_to do |format|
      format.html { redirect_to business_sizes_url }
      format.json { head :no_content }
    end
  end
end

Rails/app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.json
  def new
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(params[:competition])

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render json: @competition, status: :created, location: @competition }
      else
        format.html { render action: "new" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.json
  def update
    @competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end
end

Rails/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/app/helpers/business_sizes_helper.rb
module BusinessSizesHelper
end

Rails/app/helpers/competitions_helper.rb
module CompetitionsHelper
end

Rails/app/helpers/teams_helper.rb
module TeamsHelper
end

Rails/app/views/business_sizes/_form.html.erb
<%= form_for(@business_size) do |f| %>
  <% if @business_size.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_size.errors.count, "error") %> prohibited this business_size from being saved:</h2>

      <ul>
      <% @business_size.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/app/views/business_sizes/edit.html.erb
<h1>Editing business_size</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_size %> |
<%= link_to 'Back', business_sizes_path %>

Rails/app/views/business_sizes/index.html.erb
<h1>Listing business_sizes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @business_sizes.each do |business_size| %>
  <tr>
    <td><%= business_size.name %></td>
    <td><%= business_size.description %></td>
    <td><%= link_to 'Show', business_size %></td>
    <td><%= link_to 'Edit', edit_business_size_path(business_size) %></td>
    <td><%= link_to 'Destroy', business_size, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business size', new_business_size_path %>

Rails/app/views/business_sizes/new.html.erb
<h1>New business_size</h1>

<%= render 'form' %>

<%= link_to 'Back', business_sizes_path %>

Rails/app/views/business_sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @business_size.name %>
</p>

<p>
  <b>Description:</b>
  <%= @business_size.description %>
</p>


<%= link_to 'Edit', edit_business_size_path(@business_size) %> |
<%= link_to 'Back', business_sizes_path %>

Rails/app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

Rails/app/views/competitions/index.html.erb
<h1>Listing competitions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @competitions.each do |competition| %>
  <tr>
    <td><%= competition.name %></td>
    <td><%= competition.description %></td>
    <td><%= competition.startdate %></td>
    <td><%= competition.enddate %></td>
    <td><%= link_to 'Show', competition %></td>
    <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
    <td><%= link_to 'Destroy', competition, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Competition', new_competition_path %>

Rails/app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

Rails/app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @competition.name %>
</p>

<p>
  <b>Description:</b>
  <%= @competition.description %>
</p>

<p>
  <b>Startdate:</b>
  <%= @competition.startdate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @competition.enddate %>
</p>


<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>

Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bca</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>